package jdl.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Entity_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new application_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new config_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x766c9d72d59e4ba7L, 0xa509f4dfc71d899eL, 0x70721ca2c0e819a0L), MetaIdFactory.conceptId(0x766c9d72d59e4ba7L, 0xa509f4dfc71d899eL, 0x70721ca2c0d8934cL), MetaIdFactory.conceptId(0x766c9d72d59e4ba7L, 0xa509f4dfc71d899eL, 0x70721ca2c0d7e0e3L)).seal();
}
