package json.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Configuration_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("application");
    tgs.newLine();
    tgs.append("{");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("config");
    tgs.newLine();
    tgs.indent();
    tgs.append("{");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("baseName ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.baseName$cpeK));
    tgs.newLine();
    tgs.indent();
    tgs.append("applicationType ");
    tgs.append(SEnumOperations.getMemberName0(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.applicationType$$fEq)));
    tgs.newLine();
    tgs.indent();
    tgs.append("packageName ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.packageName$vcje));
    tgs.newLine();
    tgs.indent();
    tgs.append("authenticationType ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.authenticationType$nk4d));
    tgs.newLine();
    tgs.indent();
    tgs.append("prodDatabaseType ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.prodDatabaseType$btiq));
    tgs.newLine();
    tgs.indent();
    tgs.append("clientFramework ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.clientFramework$re5W));
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("}");
    tgs.newLine();
    tgs.indent();
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.entities$dnz8));
    tgs.indent();
    tgs.append("}");
    ctx.getBuffer().area().decreaseIndent();

  }

  private static final class PROPS {
    /*package*/ static final SProperty baseName$cpeK = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0df58f4L, 0x70721ca2c0df59c5L, "baseName");
    /*package*/ static final SProperty applicationType$$fEq = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0df58f4L, 0x70721ca2c0df5c37L, "applicationType");
    /*package*/ static final SProperty packageName$vcje = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0df58f4L, 0x70721ca2c0df6098L, "packageName");
    /*package*/ static final SProperty authenticationType$nk4d = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0df58f4L, 0x70721ca2c0df65caL, "authenticationType");
    /*package*/ static final SProperty prodDatabaseType$btiq = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0df58f4L, 0x70721ca2c0df6b99L, "prodDatabaseType");
    /*package*/ static final SProperty clientFramework$re5W = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0df58f4L, 0x70721ca2c0df7239L, "clientFramework");
    /*package*/ static final SProperty entities$dnz8 = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0df58f4L, 0x2463e97359c6433aL, "entities");
  }
}
