package json.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Entity_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("entity");
    tgs.append(" ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$zfxO));
    tgs.newLine();
    tgs.append("{");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.attribute$qk96)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode attri) {
        tgs.indent();
        tgs.append(SPropertyOperations.getString(attri, PROPS.name$byMG));
        tgs.append(" ");
        tgs.append(SPropertyOperations.getString(attri, PROPS.type$ANaD));
        tgs.append(" ");
        tgs.append(SPropertyOperations.getString(attri, PROPS.proprity$ZzMb));
        tgs.newLine();

      }
    });
    ctx.getBuffer().area().decreaseIndent();
    tgs.newLine();
    tgs.append("}");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$zfxO = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0e9f556L, 0x70721ca2c0e9f87dL, "name");
    /*package*/ static final SProperty name$byMG = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0eb538eL, 0x70721ca2c0eb5563L, "name");
    /*package*/ static final SProperty type$ANaD = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0eb538eL, 0x70721ca2c0eb5739L, "type");
    /*package*/ static final SProperty proprity$ZzMb = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0eb538eL, 0x70721ca2c0eb59fbL, "proprity");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink attribute$qk96 = MetaAdapterFactory.getContainmentLink(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0e9f556L, 0x70721ca2c0eb6808L, "attribute");
  }
}
