package json.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Enumeration_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("enum ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$DezI));
    tgs.append(" {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.enum_attribute$5cBK)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode enum_attribute) {
        tgs.append(SPropertyOperations.getString(enum_attribute, PROPS.enumKey$yiZy));
        tgs.append("( ");
        tgs.append(SPropertyOperations.getString(enum_attribute, PROPS.enumValue$7s1E));
        tgs.append(" )");
        if (SNodeOperations.getNextSibling(enum_attribute) != null) {
          tgs.append(",");
        }
      }
    });
    ctx.getBuffer().area().decreaseIndent();
    tgs.newLine();
    tgs.append("}");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$DezI = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x11299d5d780b3071L, 0x11299d5d780b32e2L, "name");
    /*package*/ static final SProperty enumKey$yiZy = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x11299d5d780c6b1bL, 0x11299d5d780c8f93L, "enumKey");
    /*package*/ static final SProperty enumValue$7s1E = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x11299d5d780c6b1bL, 0x11299d5d780cc03fL, "enumValue");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink enum_attribute$5cBK = MetaAdapterFactory.getContainmentLink(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x11299d5d780b3071L, 0x11299d5d780c680dL, "enum_attribute");
  }
}
