package json.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class Relationship_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("relationship ");
    tgs.append(SEnumOperations.getMemberName0(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.type$NyYd)));
    tgs.newLine();
    tgs.append("{");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.entity1$BEvG), PROPS.name$zfxO));
    tgs.append(" to ");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.entity2$Bqet), PROPS.name$zfxO));
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("}");

  }

  private static final class PROPS {
    /*package*/ static final SProperty type$NyYd = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0xae19d5f4fa4b2f1L, 0xae19d5f4fa4b4f3L, "type");
    /*package*/ static final SProperty name$zfxO = MetaAdapterFactory.getProperty(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0e9f556L, 0x70721ca2c0e9f87dL, "name");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink entity1$BEvG = MetaAdapterFactory.getReferenceLink(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0xae19d5f4fa4b2f1L, 0xae19d5f4fa4bfdcL, "entity1");
    /*package*/ static final SReferenceLink entity2$Bqet = MetaAdapterFactory.getReferenceLink(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0xae19d5f4fa4b2f1L, 0xae19d5f4fa7af7eL, "entity2");
  }
}
