package json.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_attribute_types_supported extends EnumerationDescriptorBase {

  public EnumerationDescriptor_attribute_types_supported() {
    super(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x11299d5d7809625cL, "attribute_types_supported", "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461312092");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_String_0 = new EnumerationDescriptor.MemberDescriptor("String", "String", 0x11299d5d7809625dL, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461312093");
  private final EnumerationDescriptor.MemberDescriptor myMember_Integer_0 = new EnumerationDescriptor.MemberDescriptor("Integer", "Integer", 0x11299d5d7809651dL, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461312797");
  private final EnumerationDescriptor.MemberDescriptor myMember_Long_0 = new EnumerationDescriptor.MemberDescriptor("Long", "Long", 0x11299d5d78096674L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461313140");
  private final EnumerationDescriptor.MemberDescriptor myMember_BigDecimal_0 = new EnumerationDescriptor.MemberDescriptor("BigDecimal", "BigDecimal", 0x11299d5d780966e0L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461313248");
  private final EnumerationDescriptor.MemberDescriptor myMember_Float_0 = new EnumerationDescriptor.MemberDescriptor("Float", "Float", 0x11299d5d780967d1L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461313489");
  private final EnumerationDescriptor.MemberDescriptor myMember_Double_0 = new EnumerationDescriptor.MemberDescriptor("Double", "Double", 0x11299d5d78096874L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461313652");
  private final EnumerationDescriptor.MemberDescriptor myMember_Enum_0 = new EnumerationDescriptor.MemberDescriptor("Enum", "Enum", 0x11299d5d7809694cL, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461313868");
  private final EnumerationDescriptor.MemberDescriptor myMember_Boolean_0 = new EnumerationDescriptor.MemberDescriptor("Boolean", "Boolean", 0x11299d5d780969f1L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461314033");
  private final EnumerationDescriptor.MemberDescriptor myMember_LocalDate_0 = new EnumerationDescriptor.MemberDescriptor("LocalDate", "LocalDate", 0x11299d5d78096ab1L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461314225");
  private final EnumerationDescriptor.MemberDescriptor myMember_ZonedDateTime_0 = new EnumerationDescriptor.MemberDescriptor("ZonedDateTime", "ZonedDateTime", 0x11299d5d78096b23L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461314339");
  private final EnumerationDescriptor.MemberDescriptor myMember_Instant_0 = new EnumerationDescriptor.MemberDescriptor("Instant", "Instant", 0x11299d5d78096c34L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461314612");
  private final EnumerationDescriptor.MemberDescriptor myMember_Duration_0 = new EnumerationDescriptor.MemberDescriptor("Duration", "Duration", 0x11299d5d78096cc2L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461314754");
  private final EnumerationDescriptor.MemberDescriptor myMember_UUID_0 = new EnumerationDescriptor.MemberDescriptor("UUID", "UUID", 0x11299d5d78096d86L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461314950");
  private final EnumerationDescriptor.MemberDescriptor myMember_Blob_0 = new EnumerationDescriptor.MemberDescriptor("Blob", "Blob", 0x11299d5d78096e4bL, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461315147");
  private final EnumerationDescriptor.MemberDescriptor myMember_AnyBlob_0 = new EnumerationDescriptor.MemberDescriptor("AnyBlob", "AnyBlob", 0x11299d5d78096f7aL, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461315450");
  private final EnumerationDescriptor.MemberDescriptor myMember_ImageBlob_0 = new EnumerationDescriptor.MemberDescriptor("ImageBlob", "ImageBlob", 0x11299d5d78097076L, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461315702");
  private final EnumerationDescriptor.MemberDescriptor myMember_TextBlob_0 = new EnumerationDescriptor.MemberDescriptor("TextBlob", "TextBlob", 0x11299d5d780970efL, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/1236692597461315823");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x11299d5d7809625cL, 0x11299d5d7809625dL, 0x11299d5d7809651dL, 0x11299d5d78096674L, 0x11299d5d780966e0L, 0x11299d5d780967d1L, 0x11299d5d78096874L, 0x11299d5d7809694cL, 0x11299d5d780969f1L, 0x11299d5d78096ab1L, 0x11299d5d78096b23L, 0x11299d5d78096c34L, 0x11299d5d78096cc2L, 0x11299d5d78096d86L, 0x11299d5d78096e4bL, 0x11299d5d78096f7aL, 0x11299d5d78097076L, 0x11299d5d780970efL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_String_0, myMember_Integer_0, myMember_Long_0, myMember_BigDecimal_0, myMember_Float_0, myMember_Double_0, myMember_Enum_0, myMember_Boolean_0, myMember_LocalDate_0, myMember_ZonedDateTime_0, myMember_Instant_0, myMember_Duration_0, myMember_UUID_0, myMember_Blob_0, myMember_AnyBlob_0, myMember_ImageBlob_0, myMember_TextBlob_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "String":
        return myMember_String_0;
      case "Integer":
        return myMember_Integer_0;
      case "Long":
        return myMember_Long_0;
      case "BigDecimal":
        return myMember_BigDecimal_0;
      case "Float":
        return myMember_Float_0;
      case "Double":
        return myMember_Double_0;
      case "Enum":
        return myMember_Enum_0;
      case "Boolean":
        return myMember_Boolean_0;
      case "LocalDate":
        return myMember_LocalDate_0;
      case "ZonedDateTime":
        return myMember_ZonedDateTime_0;
      case "Instant":
        return myMember_Instant_0;
      case "Duration":
        return myMember_Duration_0;
      case "UUID":
        return myMember_UUID_0;
      case "Blob":
        return myMember_Blob_0;
      case "AnyBlob":
        return myMember_AnyBlob_0;
      case "ImageBlob":
        return myMember_ImageBlob_0;
      case "TextBlob":
        return myMember_TextBlob_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
