package json.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_applicationType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_applicationType() {
    super(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0e7812dL, "applicationType", "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/8102570164939620653");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_microservice_0 = new EnumerationDescriptor.MemberDescriptor("microservice", "microservice", 0x70721ca2c0e7812eL, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/8102570164939620654");
  private final EnumerationDescriptor.MemberDescriptor myMember_gateway_0 = new EnumerationDescriptor.MemberDescriptor("gateway", "gateway", 0x70721ca2c0e7843cL, "r:d7a2d3ee-8e24-49f3-b446-7a6ae06181e3(json.structure)/8102570164939621436");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x52d66a050b8e4c9cL, 0xa51ced22033bbbf3L, 0x70721ca2c0e7812dL, 0x70721ca2c0e7812eL, 0x70721ca2c0e7843cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_microservice_0, myMember_gateway_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "microservice":
        return myMember_microservice_0;
      case "gateway":
        return myMember_gateway_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
